export default {
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  ADD_CURRENT_USER: 'ADD_CURRENT_USER',
  UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
  GET_USERS: 'GET_USERS',
  GET_USER_BY_ID: 'GET_USER_BY_ID',
  SHOW_LOADER: 'SHOW_LOADER',
  GET_POST_BY_ID: 'GET_POST_BY_ID',
  GET_FEED: 'GET_FEED',
}