export default {
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  ADD_CURRENT_USER: 'ADD_CURRENT_USER',
  UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',
  CREATE_POST: 'CREATE_POST',
  GET_USERS: 'GET_USERS',
}